/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const NButton: typeof import('naive-ui')['NButton']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NTag: typeof import('naive-ui')['NTag']
  const NTooltip: typeof import('naive-ui')['NTooltip']
}
