/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBatchDetails: typeof import('./src/components/batch/AppBatchDetails.vue')['default']
    AppCreateBatch: typeof import('./src/components/batch/AppCreateBatch.vue')['default']
    AppCreateOutflow: typeof import('./src/components/outflow/AppCreateOutflow.vue')['default']
    AppCreateSeed: typeof import('./src/components/seed/AppCreateSeed.vue')['default']
    AppEditBatch: typeof import('./src/components/batch/AppEditBatch.vue')['default']
    AppEditOutflow: typeof import('./src/components/outflow/AppEditOutflow.vue')['default']
    AppFileUpload: typeof import('./src/components/AppFileUpload.vue')['default']
    AppRemoveBatch: typeof import('./src/components/batch/AppRemoveBatch.vue')['default']
    AppRemoveOutflow: typeof import('./src/components/outflow/AppRemoveOutflow.vue')['default']
    AppSettings: typeof import('./src/components/AppSettings.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NImage: typeof import('naive-ui')['NImage']
    NModal: typeof import('naive-ui')['NModal']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
