import { GlobalThemeOverrides } from 'naive-ui';

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#04853a',
    primaryColorHover: '#03682e',
    primaryColorPressed: '#03582a',
    primaryColorSuppl: '#04853a',
    fontFamily: 'Inter, Avenir, Helvetica, Arial, sans-serif',
    fontWeight: '400',
    fontWeightStrong: '600',
    infoColor: '#1976d2',
    successColor: '#3a7109',
    warningColor: '#9f764a',
    errorColor: '#d32f2f',
    borderRadius: '8px',
    fontSize: '16px',
    lineHeight: '24px',
    textColorBase: '#0f0f0f',
    bodyColor: '#f5f5f5',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    dividerColor: '#e0e0e0',
    borderColor: '#e0e0e0',
    placeholderColor: '#8a8a8a',
    inputColor: '#ffffff',
  },
  Layout: {
    color: '#f5f5f5',
    siderColor: '#f5f5f5',
    headerColor: '#f5f5f5',
    footerColor: '#f5f5f5',
    contentColor: '#f5f5f5',
  },
  Button: {
    textColor: '#0f0f0f',
    rippleColor: 'transparent',
    colorHover: '#f2f2f2',
    border: 'none',
    borderFocus: 'none',
    borderHover: 'none',
    borderPressed: 'none',
    textColorFocus: '#0f0f0f',
    textColorHover: '#0f0f0f',
    textColorPressed: '#0f0f0f',
    textColorSuppl: '#0f0f0f',
    textColorText: '#0f0f0f',
  },
};

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#ffffff',
    primaryColorHover: '#d1d1d1',
    primaryColorPressed: '#bbbbbb',
    primaryColorSuppl: '#ffffff',
    fontFamily: 'Inter, Avenir, Helvetica, Arial, sans-serif',
    fontWeight: '400',
    fontWeightStrong: '600',
    infoColor: '#1976d2',
    successColor: '#3a7109',
    warningColor: '#9f764a',
    errorColor: '#d32f2f',
    borderRadius: '8px',
    fontSize: '16px',
    lineHeight: '24px',
    textColorBase: '#f6f6f6',
    bodyColor: '#2f2f2f',
    cardColor: '#1e1e1e',
    modalColor: '#2f2f2f',
    popoverColor: '#2f2f2f',
    tableColor: '#2f2f2f',
    dividerColor: '#444444',
    borderColor: '#444444',
    placeholderColor: '#9e9e9e',
    inputColor: '#2f2f2f',
  },
  Layout: {
    color: '#2f2f2f',
    siderColor: '#2f2f2f',
    headerColor: '#2f2f2f',
    footerColor: '#2f2f2f',
    contentColor: '#2f2f2f',
  },
  Button: {
    textColor: '#ffffff',
    rippleColor: 'transparent',
    colorHover: '#3a3a3a',
    border: 'none',
    borderFocus: 'none',
    borderHover: 'none',
    borderPressed: 'none',
    textColorFocus: '#ffffff',
    textColorHover: '#ffffff',
    textColorPressed: '#ffffff',
    textColorSuppl: '#ffffff',
    textColorText: '#ffffff',
  },
};
